name: Docker Build Dev

on:
  push:
    branches:
      - dev
      
permissions:
  contents: read
  packages: write

jobs:
  build-and-push-dev:
    name: Build & Push Dev ${{ matrix.service }}
    runs-on: ubuntu-latest
    strategy:
       matrix:
        include:
          - service: auth-service
            context: .
            dockerfile: ./auth-service/Dockerfile
          - service: project-service
            context: .
            dockerfile: ./project-service/Dockerfile
          - service: task-service
            context: .
            dockerfile: ./task-service/Dockerfile
          - service: notification-service
            context: .
            dockerfile: ./notification-service/Dockerfile
          - service: frontend
            context: ./frontend
            dockerfile: ./frontend/Dockerfile

    steps:
      - uses: actions/checkout@v4

      - name: Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f

      - name: Login GitHub Container Registry
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image name
        run: |
          echo "IMAGE_NAME=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build & Push dev image
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8
        with:
          context: ./${{ matrix.service }}
          file: ${{ matrix.dockerfile }}
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/${{ env.IMAGE_NAME }}/${{ matrix.service }}:dev
            ghcr.io/${{ env.IMAGE_NAME }}/${{ matrix.service }}:sha-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max